# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

name: Azure Pipelines
variables:
  python.version: '3.7.6'
  terraform.version: '0.13.4'
stages:
- stage: Provisioning
  displayName: Provisioning
  jobs: 
  - job: ProvisioningAppService
    displayName: Provisioning AppService
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.13.4'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        backendServiceArm: 'Azure subscription 1(09998214-d1cb-445d-a0c2-6e0ebc67bd65)'
        #backendAzureRmResourceGroupName: "terraform"
        #backendAzureRmStorageAccountName: "tstate10"
        #backendAzureRmContainerName: "tstate"
        #backendAzureRmKey: "terraform.tfstate"

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
